import { IBrick } from '../types/IBrick';
import { BallMode } from '../types/IPaddle';

export const backUpBricks: IBrick[] = [
  {
    id: 1,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 2,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 3,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 4,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 5,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 6,
    bonusName: BallMode.Power,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 7,
    bonusName: BallMode.Power,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 8,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 9,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 10,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 11,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 12,
    bonusName: BallMode.Power,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 13,
    bonusName: BallMode.Power,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 14,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 15,
    bonusName: BallMode.Speed,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 16,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 17,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 18,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 19,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 20,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
  {
    id: 21,
    bonusName: BallMode.Default,
    brick: null,
    status: true,
    hitCount: 2,
  },
];
